import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: "#f3f5f8",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#f3f5f8",
  },
  safeAreaDark: {
    backgroundColor: "#05070b",
  },
  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  headerSide: {
    width: 72,
    justifyContent: "center",
  },
  headerSideRight: {
    alignItems: "flex-end",
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
    color: "#0f172a",
  },
  headerTitleDark: {
    color: "#ffffff",
  },
  iconButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  headerChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: "#2f89ef",
  },
  headerChipText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "700",
  },
  centerWrap: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 22,
    paddingBottom: 36,
  },
  scrollBody: {
    paddingHorizontal: 22,
    paddingBottom: 34,
  },
  authCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 22,
    gap: 16,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  brand: {
    fontSize: 22,
    fontWeight: "800",
    color: "#2f89ef",
  },
  authTitle: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "800",
    color: "#0f172a",
  },
  authSubtitle: {
    color: "#64748b",
    lineHeight: 21,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
  },
  input: {
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#dbe3ef",
    paddingHorizontal: 14,
    fontSize: 14,
    color: "#0f172a",
  },
  textarea: {
    minHeight: 98,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  primaryButton: {
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2f89ef",
    marginTop: 4,
  },
  primaryButtonCompact: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 16,
  },
  primaryButtonDisabled: {
    backgroundColor: "#9ac1f7",
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#ffffff",
  },
  primaryButtonTextCompact: {
    fontSize: 12,
  },
  linkText: {
    textAlign: "center",
    color: "#64748b",
    fontSize: 12,
  },
  uploadPlaceholder: {
    minHeight: 110,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#b8c2cf",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 20,
  },
  uploadPlaceholderText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#334155",
  },
  uploadPlaceholderSubText: {
    fontSize: 12,
    color: "#64748b",
  },
  uploadPreview: {
    width: "100%",
    height: 120,
    borderRadius: 12,
  },
  completeWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
    gap: 18,
  },
  completeIcon: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "#22c55e",
    alignItems: "center",
    justifyContent: "center",
  },
  completeTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0f172a",
  },
  completeDescription: {
    textAlign: "center",
    color: "#64748b",
    lineHeight: 21,
  },
  topBrandRow: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoutButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: "#2f89ef",
  },
  logoutButtonText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "700",
  },
  bannerWrap: {
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  bannerText: {
    flex: 1,
    color: "#1d4ed8",
    fontSize: 12,
    lineHeight: 17,
  },
  homeScroll: {
    paddingHorizontal: 10,
    paddingBottom: 96,
    gap: 12,
  },
  homeCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 14,
    gap: 12,
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  homeCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardCategory: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
  },
  cardImageWrap: {
    height: 146,
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  cardImage: {
    width: "88%",
    height: "88%",
  },
  cardTitle: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  loaderCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    gap: 10,
    paddingVertical: 24,
  },
  loaderText: {
    color: "#64748b",
    fontSize: 13,
  },
  bottomTab: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 74,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    gap: 4,
  },
  tabText: {
    fontSize: 10,
    color: "#9aa4b2",
  },
  tabTextActive: {
    color: "#2f89ef",
    fontWeight: "700",
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  listScroll: {
    paddingHorizontal: 12,
    paddingBottom: 96,
    gap: 10,
  },
  listCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 10,
  },
  listThumb: {
    width: 72,
    height: 72,
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  listThumbImage: {
    width: "88%",
    height: "88%",
  },
  listBody: {
    flex: 1,
    gap: 4,
  },
  listName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  listCode: {
    fontSize: 12,
    color: "#475569",
  },
  listLocation: {
    fontSize: 11,
    color: "#94a3b8",
  },
  listSide: {
    alignItems: "flex-end",
    gap: 6,
  },
  scannerWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 16,
  },
  scannerTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "800",
  },
  scannerCode: {
    color: "#93c5fd",
    fontSize: 13,
    fontWeight: "700",
  },
  scannerFrame: {
    width: 210,
    height: 210,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.35)",
    position: "relative",
    overflow: "hidden",
  },
  scannerCamera: {
    ...StyleSheet.absoluteFillObject,
  },
  scannerPermissionBox: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.7)",
    padding: 18,
  },
  scannerPermissionText: {
    color: "#ffffff",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 20,
  },
  scannerCorner: {
    position: "absolute",
    width: 32,
    height: 32,
    borderColor: "#ffffff",
  },
  cornerLeftTop: {
    top: -1,
    left: -1,
    borderTopWidth: 3,
    borderLeftWidth: 3,
  },
  cornerRightTop: {
    top: -1,
    right: -1,
    borderTopWidth: 3,
    borderRightWidth: 3,
  },
  cornerLeftBottom: {
    left: -1,
    bottom: -1,
    borderLeftWidth: 3,
    borderBottomWidth: 3,
  },
  cornerRightBottom: {
    right: -1,
    bottom: -1,
    borderRightWidth: 3,
    borderBottomWidth: 3,
  },
  scannerGuide: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  scannerSubGuide: {
    color: "#d1d5db",
    textAlign: "center",
    lineHeight: 19,
    fontSize: 12,
    marginBottom: 6,
  },
  detailScroll: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 96,
    gap: 12,
  },
  detailCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 15,
    gap: 12,
  },
  detailImageWrap: {
    height: 132,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  detailImage: {
    width: "88%",
    height: "88%",
  },
  detailName: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  detailCode: {
    textAlign: "center",
    fontSize: 26,
    fontWeight: "800",
    color: "#0f172a",
  },
  detailInfoBox: {
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    padding: 12,
    gap: 6,
  },
  detailInfoText: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 19,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  sectionBody: {
    fontSize: 13,
    color: "#475569",
    lineHeight: 20,
  },
  quickMemoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickMemoChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#eef2ff",
  },
  quickMemoChipActive: {
    backgroundColor: "#dbeafe",
  },
  quickMemoText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#475569",
  },
  quickMemoTextActive: {
    color: "#2563eb",
  },
  submitWrap: {
    alignItems: "center",
  },
  myScroll: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 96,
    gap: 12,
  },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
  },
  avatarCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#e8f0ff",
    alignItems: "center",
    justifyContent: "center",
  },
  profileBody: {
    flex: 1,
    gap: 4,
  },
  profileName: {
    fontSize: 19,
    fontWeight: "800",
    color: "#111827",
  },
  profileMeta: {
    color: "#64748b",
    fontSize: 13,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    gap: 6,
  },
  summaryNumber: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0f172a",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#64748b",
  },
  panelCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    gap: 12,
  },
  panelHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  panelCount: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2563eb",
  },
  rentalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 10,
  },
  notificationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 10,
  },
  issueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 10,
  },
  rentalTextWrap: {
    flex: 1,
    gap: 4,
  },
  rentalTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
  },
  rentalSub: {
    fontSize: 12,
    color: "#64748b",
  },
  smallActionButton: {
    minWidth: 48,
    borderRadius: 999,
    backgroundColor: "#e8f0ff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  smallActionText: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "800",
  },
  issueBadge: {
    borderRadius: 999,
    backgroundColor: "#fff7ed",
    borderWidth: 1,
    borderColor: "#fed7aa",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  issueBadgeText: {
    color: "#c2410c",
    fontSize: 11,
    fontWeight: "800",
  },
  emptyText: {
    color: "#64748b",
    lineHeight: 19,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.35)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    maxWidth: 310,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    gap: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  modalBody: {
    color: "#475569",
    lineHeight: 21,
  },
  modalAction: {
    alignSelf: "flex-end",
    paddingTop: 4,
  },
  modalActionText: {
    color: "#2563eb",
    fontWeight: "700",
  },
});
