const USER_ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
};

const EQUIPMENT_STATUS = {
  AVAILABLE: "AVAILABLE",
  RENTAL_PENDING: "RENTAL_PENDING",
  RENTED: "RENTED",
  RETURN_PENDING: "RETURN_PENDING",
  INSPECTION_REQUIRED: "INSPECTION_REQUIRED",
  REPAIR: "REPAIR",
  OVERDUE: "OVERDUE",
};

const RENTAL_STATUS = {
  REQUESTED: "REQUESTED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXTENSION_REQUESTED: "EXTENSION_REQUESTED",
  EXTENSION_APPROVED: "EXTENSION_APPROVED",
  EXTENSION_REJECTED: "EXTENSION_REJECTED",
  RETURN_PENDING: "RETURN_PENDING",
  RETURNED: "RETURNED",
  OVERDUE: "OVERDUE",
};

const NOTIFICATION_TYPES = {
  RENTAL_REQUEST: "RENTAL_REQUEST",
  RENTAL_APPROVED: "RENTAL_APPROVED",
  RENTAL_REJECTED: "RENTAL_REJECTED",
  EXTENSION_REQUEST: "EXTENSION_REQUEST",
  EXTENSION_APPROVED: "EXTENSION_APPROVED",
  EXTENSION_REJECTED: "EXTENSION_REJECTED",
  RETURN_REQUESTED: "RETURN_REQUESTED",
  RETURN_APPROVED: "RETURN_APPROVED",
  RETURN_INSPECTION: "RETURN_INSPECTION",
  RETURN_REPAIR: "RETURN_REPAIR",
  DUE_3_DAYS: "DUE_3_DAYS",
  DUE_1_DAY: "DUE_1_DAY",
  DUE_TODAY: "DUE_TODAY",
  OVERDUE: "OVERDUE",
};

const RENTAL_REQUEST_BLOCKING_STATUSES = [
  RENTAL_STATUS.REQUESTED,
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.EXTENSION_REQUESTED,
  RENTAL_STATUS.EXTENSION_APPROVED,
  RENTAL_STATUS.EXTENSION_REJECTED,
  RENTAL_STATUS.RETURN_PENDING,
  RENTAL_STATUS.OVERDUE,
];

const ACTIVE_RENTAL_STATUSES = [
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.EXTENSION_REQUESTED,
  RENTAL_STATUS.EXTENSION_APPROVED,
  RENTAL_STATUS.EXTENSION_REJECTED,
  RENTAL_STATUS.RETURN_PENDING,
  RENTAL_STATUS.OVERDUE,
];

const RETURN_REQUESTABLE_RENTAL_STATUSES = [
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.EXTENSION_APPROVED,
  RENTAL_STATUS.EXTENSION_REJECTED,
  RENTAL_STATUS.OVERDUE,
];

const EXTENSION_REQUESTABLE_RENTAL_STATUSES = [
  RENTAL_STATUS.APPROVED,
  RENTAL_STATUS.EXTENSION_APPROVED,
  RENTAL_STATUS.EXTENSION_REJECTED,
  RENTAL_STATUS.OVERDUE,
];

const ACTIVE_EQUIPMENT_STATUSES = [
  EQUIPMENT_STATUS.RENTED,
  EQUIPMENT_STATUS.OVERDUE,
];

module.exports = {
  USER_ROLES,
  EQUIPMENT_STATUS,
  RENTAL_STATUS,
  NOTIFICATION_TYPES,
  ACTIVE_RENTAL_STATUSES,
  RENTAL_REQUEST_BLOCKING_STATUSES,
  RETURN_REQUESTABLE_RENTAL_STATUSES,
  EXTENSION_REQUESTABLE_RENTAL_STATUSES,
  ACTIVE_EQUIPMENT_STATUSES,
};
